language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false

deploy:
  provider: npm
  email: "lihegaozhong@gmail.com"
  api_key: "0b0c9b47-769c-40cd-923a-69a861a0bb7d"
  on:
    tags: true
before_script:
  - npm prune
script:
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/