language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- '8'
before_script:
- npm prune
script: 
before_install:
- ssh-keygen -R 139.199.201.19
- openssl aes-256-cbc -K $encrypted_c7c84622e0dd_key -iv $encrypted_c7c84622e0dd_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval `ssh-agent -s`
- chmod 600 deploy_rsa
- echo "139.199.201.19 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBE0GREVg01TWLK3CO3qtXuC0WL2ibBRmhsVINmcDFwrMAaSKaajH91+MeozjV1ZV8zIfgza7D0OVTax0Oq/Qoyg=" >> ~/.ssh/known_hosts
- ssh-add deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist root@139.199.201.19:pageBuilder/
  on:
    branch: master
after_success:
- npm run semantic-release
branches:
  only:
  - master
