language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- '8'
before_script:
- npm prune
script: 
after_success:
- npm run semantic-release
branches:
  only:
  - master
before_deploy:
- openssl aes-256-cbc -K $encrypted_c7c84622e0dd_key -iv $encrypted_c7c84622e0dd_iv
  -in travis_rsa.enc -out /temp/travis_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/travis_rsa
- ssh-add /tmp/travis_rsa